# GitHub action based on https://github.com/actions/stale

name: 'Close stale issues and PRs'
on:
  schedule:
    # Execute every hour
    - cron: '0 * * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  close-pending:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          # GLOBAL ------------------------------------------------------------
          operations-per-run: 30
          exempt-all-milestones: true
          days-before-stale: -1
          only-issue-labels: 'pending:reproducer'
          only-pr-labels: 'pending:dco'

          # ISSUES ------------------------------------------------------------
          days-before-issue-close: 7
          stale-issue-label: 'pending:reproducer'
          close-issue-label: 'closed:unreproducible'
          close-issue-message: >
            While we asked for a reproducer, none was provided. If you provide a valid reproducer, we will consider this issue again.
            In the meantime, closing as unreproducible.

          # PULL REQUESTS -----------------------------------------------------
          days-before-pr-close: 7
          stale-pr-label: 'pending:dco'
          close-pr-label: 'closed:missing-dco'
          close-pr-message: >
            While we asked sign your commits, it has not been done. If you sign your commits, we will consider this pull request again.
            In the meantime, closing as missing DCO (see the [Developer Certificate of Origin](https://probot.github.io/apps/dco/) GitHub app).
